apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: {{ .Values.app.ingress.className | quote }}
spec:
  rules:
    - host: {{ .Values.app.ingress.hosts.stable | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.app.name }}
                port:
                  number: {{ .Values.app.service.port }}
