apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.model.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.model.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.model.name }}
    spec:
      containers:
        - name: {{ .Values.model.name }}
          image: "{{ .Values.model.image.repository }}:{{ .Values.model.image.tag }}"
          ports:
            - containerPort: {{ .Values.model.port }}
          env:
            - name: MODEL_SERVICE_PORT
              value: "{{ .Values.model.port }}"
          volumeMounts:
            - name: model-output
              mountPath: /models
      volumes:
        - name: model-output
          emptyDir: {}
