# TODO: placeholder values will be replaced with values from the value.xml file (by person 5 during the helm templating step)

apiVersion: v1
kind: Secret
metadata:
  name: secret                      # replace
type: Opaque
stringData:
  SMTP_USER: "placeholder-user"     # replace
  SMTP_PASS: "placeholder-password" # replace
