---
- hosts: node-*
  become: yes
  tasks:
    - name: Install Worker Dependencies (Placeholder)
      debug:
        msg: "This is where Kubernetes Worker setup happens."

    - name: Check if worker node already joined the cluster
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    # Step 18
    - name: Generate kubeadm join command on controller
      ansible.builtin.command: kubeadm token create --print-join-command
      delegate_to: ctrl
      register: join_cmd
      when: not kubelet_conf.stat.exists

    # Step 19
    - name: Join worker node to the Kubernetes cluster
      ansible.builtin.shell: "{{ join_cmd.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: not kubelet_conf.stat.exists